# Generated by Django 3.2 on 2022-09-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='personal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
