# Generated by Django 3.2 on 2022-09-29 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oficina', '0002_oficina_personal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oficina',
            name='personal',
        ),
    ]
